server:
  port: 9092
spring:
  application: { name: 'flex83-devices-be' }

hibernate:
  connection :
    url:  jdbc:mysql://localhost:3306/flex83_devices?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: ticket@123
    driver_class: com.mysql.jdbc.Driver
  dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  mt_url: jdbc:mysql://localhost:3306/__DATABASE__?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false";